FROM alpine:latest as build

COPY . /code

# Add build tools
RUN apk add --update alpine-sdk openssl-dev

# Build ff
RUN cd /code && \
   LD=gcc CC=gcc \
   ifeq ($(FF_OPTIMIZE), 1) \
   OPTIMISE_FLAGS=-O3 -DFF_OPTIMIZE=1\
   else
   OPTIMISE_FLAGS=-O0\
   endif\

CC_FLAGS=-Wall -Wextra -std=c99 -D_GNU_SOURCE $(OPTIMISE_FLAGS) $(CCFLAGS)
LD_FLAGS=$(LDFLAGS)
SERVER_LIBS=-lm -lssl -lcrypto -lpthread
CLIENT_LIBS=-lssl -lcrypto


FROM alpine:latest

# Install dependencies
RUN apk add --update openssl

COPY --from=build /usr/local/bin/ff /usr/local/bin/ff
COPY --from=build /usr/local/bin/ff_client /usr/local/bin/ff_client

ENTRYPOINT [ "ff" ]
